name: Create and publish a Docker image
on:
  push:
    branches:
      - $default-branch
    tags:
      - v*
      - dev
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY_NAME: ghcr.io
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Build executable package
        run: |
          cd "${GITHUB_WORKSPACE}"
          npm ci
          npm run build
          test -e ./dist/server.bin
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY_NAME }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get release version
        run: echo "RELEASE_VERSION=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY_NAME }}/${{ github.repository }}:${{ env.RELEASE_VERSION }}
            ${{ env.REGISTRY_NAME }}/${{ github.repository }}:latest
          file: ./deploy/fastfinder/Dockerfile
